### ISSUE TITLE
MAC OS CAPITAN

### ISSUE THREAD

**Issue by adriendoux** [suite22/cinemetrics#16]
Dear suite22,

I've been trying to make Frederic's code work but, being a neophyte, I rapidly realised I didn't know how. Seeing your step-by-step-all-inclusive solution raised my hopes but I failed pathetically one more time. 
I downloaded Vagrant and "vagranted" it up but the box, (after installing virtual box, vmware fusion and parallels). I then "sshed up" and got a "Welcome to Ubuntu message" which I think means I'm connected to your VM. But when I type the : 

"python 01_1_new-project.py VISITE STEPHANE SALSA copy.m4v" 

I get a :  

"python: can't open file '01_1_new-project.py': [Errno 2] No such file or directory ".

I need to say that in my "vagrant" folder i have a "bin" and an "embedded" folder but no "data folder". So naturally I tried placing my video in the three but to no avail.   

I don't know what else to do due to my lack of competence. Can you give me a hand?

Adrien

**Comment by suite22** [comment]
Hi @adriendoux,
It looks like the folder is named `vagrant-data` now https://github.com/suite22/cinemetrics/blob/master/Vagrantfile#L50
I haven't looked at it in a while.

Once you SSH in, use `ls` to see where you are in the folder structure. Let me know if `vagrant-data` isn't one of those options.

Cheers

**Comment by adriendoux** [comment]
Dear Ben,

thanks fo your reply. Unfortunately I can seem to locate the vagrant-data file. I’ve included a shot of what I’m doing.

Adrien DOUX

**Comment by suite22** [comment]
@adriendoux take a look at the changes I just made to the readme file. Let me know if that helps.
